output_dir: "tuned-model"

bittensor:
  network: "nobunaga"

dataset:
  # either 'bittensor', a local path, or one from huggingface
  name: "bittensor"
  config_name: null # necessary for huggingface datasets
  num_batches: 10
  block_size: null # if null, defaults to bittensor's validator sequence length.

  overwrite_cache: false
  keep_linebreaks: true
  concatenate_raw: false # only really necessary when loading a local .txt file
  load_tokenized_data: true

model:
  name: gpt2
  config_name: null

tokenizer:
  name: null
  use_fast: true
  preprocessing_num_workers: 128
  pad_token: "[PAD]"

training:
  seed: 17
  val_split_percent: 5

  # if null these both default to bittensor's validator batch size
  train_batch_size: null
  eval_batch_size: null

  learning_rate: 1e-5
  weight_decay: 0.1
  num_epochs: 1
  max_train_steps: null
  gradient_accumulation_steps: 2
  lr_scheduler: "constant" # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
  lr_warmup_steps: 10
  eval_every: 250
  max_eval_steps: 500

  checkpoint:
    resume_from_checkpoint: 0 # integer representing which checkpoint to load from, or <= 0 to not
    every_n_steps: null

tracking:
  enabled: true
  report_to: "all"

testing:
  enabled: false

keys:
  WANDB_KEY: null
  HF_access_token: null